"""VENDOR-ONLY tool. Never ship this or the private key with the installer.

  python -m tools.license_issuer gen-keys [--out keys] [--force]
  python -m tools.license_issuer issue --machine RTL-... --buyer "Name" --expires 2027-09-30 [--plan standard]
"""
import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat, PublicFormat

from retail import clock
from retail.license import b64e


def generate_keypair():
    private = Ed25519PrivateKey.generate()
    raw_private = private.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())
    raw_public = private.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    return raw_private, raw_public


def issue(private_key, *, machine, buyer, expires, plan="standard"):
    if not isinstance(machine, str) or not machine.strip():
        raise ValueError("machine must be a non-empty string")
    if not isinstance(buyer, str) or not buyer.strip():
        raise ValueError("buyer must be a non-empty string")
    if not isinstance(plan, str) or not plan.strip():
        raise ValueError("plan must be a non-empty string")
    machine, buyer, plan = machine.strip(), buyer.strip(), plan.strip()
    if not isinstance(expires, str):
        raise ValueError("expires must be an ISO date string like 2027-09-30")
    try:
        expiry_date = date.fromisoformat(expires)
    except ValueError:
        raise ValueError("expires must be an ISO date string like 2027-09-30") from None
    if expiry_date.isoformat() != expires:
        raise ValueError("expires must be an ISO date string like 2027-09-30")
    if expiry_date < clock.today():
        raise ValueError(f"expires {expires} is already in the past")
    payload = json.dumps(
        {"machine": machine, "buyer": buyer, "expires": expires, "plan": plan},
        sort_keys=True, separators=(",", ":"),
    ).encode("utf-8")
    signature = Ed25519PrivateKey.from_private_bytes(private_key).sign(payload)
    return f"{b64e(payload)}.{b64e(signature)}"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="license_issuer")
    sub = parser.add_subparsers(dest="cmd", required=True)
    gen = sub.add_parser("gen-keys")
    gen.add_argument("--out", default="keys")
    gen.add_argument("--force", action="store_true",
                     help="replace an existing retail/public_key.py (invalidates every key already issued)")
    iss = sub.add_parser("issue")
    iss.add_argument("--private", default="keys/private.key")
    iss.add_argument("--machine", required=True)
    iss.add_argument("--buyer", required=True)
    iss.add_argument("--expires", required=True, help="YYYY-MM-DD")
    iss.add_argument("--plan", default="standard")
    args = parser.parse_args(argv)

    if args.cmd == "gen-keys":
        target = Path(args.out) / "private.key"
        public_path = Path("retail/public_key.py")
        if not public_path.parent.is_dir():
            print(f"Cannot find {public_path.parent}/ - run gen-keys from the project root.", file=sys.stderr)
            return 2
        if public_path.is_file() and public_path.stat().st_size > 0 and not args.force:
            print(f"Refusing to replace {public_path}: a new key pair invalidates every license key "
                  "already issued. Pass --force only if you really mean to start over.", file=sys.stderr)
            return 1
        # NOTE: on Windows POSIX mode bits (0o600/0o700) are largely ignored, so keep the key
        # in a folder only you can read (and back it up somewhere safe).
        try:
            target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        except OSError:
            pass
        private, public = generate_keypair()
        try:
            fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            print(f"Refusing to overwrite {target}. Back it up, then delete it deliberately.", file=sys.stderr)
            return 1
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(private.hex())
        public_path.write_text(
            '"""Generated by tools/license_issuer.py gen-keys. Safe to commit."""\n'
            f'PUBLIC_KEY = bytes.fromhex("{public.hex()}")\n',
            encoding="utf-8",
        )
        print(f"Private key written to {target} - back it up somewhere safe and NEVER commit or ship it.")
        return 0

    try:
        private = bytes.fromhex(Path(args.private).read_text(encoding="utf-8").strip())
    except OSError:
        print(f"Cannot read the private key file {args.private}.", file=sys.stderr)
        return 2
    except ValueError:
        print(f"{args.private} is not a valid private key (expected 64 hex characters).", file=sys.stderr)
        return 2
    if len(private) != 32:
        print(f"{args.private} is not a valid private key (expected 64 hex characters).", file=sys.stderr)
        return 2
    try:
        key = issue(private, machine=args.machine, buyer=args.buyer, expires=args.expires, plan=args.plan)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    print(key)
    return 0


if __name__ == "__main__":
    sys.exit(main())
